apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accounting-db-data
  namespace: accounting
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block