FROM php:7.2-apache

# point apt to buster archive AND disable Valid-Until checks (archive metadata is expired)
RUN echo "deb http://archive.debian.org/debian buster main" > /etc/apt/sources.list \
    && echo "deb http://archive.debian.org/debian-security buster/updates main" >> /etc/apt/sources.list \
    && printf 'Acquire::Check-Valid-Until "false";\n' > /etc/apt/apt.conf.d/99no-check-valid
  
# Install necessary extensions and dependencies
RUN apt-get update --allow-releaseinfo-change \
    && apt-get install -y --no-install-recommends \
    zip \
    unzip \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    less \
    bash-completion \
    procps \
    curl \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install mysqli pdo pdo_mysql bcmath \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd

# Enable Apache mod_rewrite
RUN a2enmod rewrite

ENV APACHE_DOCUMENT_ROOT /var/www/html/app/webroot

# Update Apache configuration
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Set working directory
WORKDIR /var/www/html

# NOTE: UNDO-THIS FOR DEV
# For prod: 
COPY ./app/apache-config/default.conf /etc/apache2/sites-available/000-default.conf
COPY . /var/www/html

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install OfxParser
RUN composer require asgrim/ofxparser

# Add your user (UID 1000) to the container
RUN useradd -u 1000 -m z

# Set permissions and change ownership to your user (UID 1000)
RUN chown -R z:z /var/www/html

# Switch to your user (UID 1000)
USER z

# Expose port 80
EXPOSE 80

CMD ["apache2-foreground"]
